Finalising create post before setup with back-end
Watt-Dev/SnapThat-PhoneApp pull request #11
Opened 2021-01-18 18:40 UTC by wrt95

Changes made: 
### types.ts
- All types needed for the project is moved into one file, types.ts. 
- Two new types, one for channel and one for user, is created. 

### mockUser.ts
- This is a file containing a dummy user-object. This user can be used to display information on posts and in the profile component. 

### ImagePicker.tsx
- State handling of images moved to parent component, CreatePost.tsx
- Image object made smaller by deleting unnecessary fields. 

### CreatePost.tsx
- Solved and fixed issue with ScrollView. Page is now scrollable. 
- Added functionality to create a new post: 
    - State handling for storing the fields created by the user, which are
        - Title
        - image path
        - caption
    - A user can no longer create a post without a title. 
    - Title must be minimum 5 characters long. 
    - When pressing create post, a validation check is performed by checking that there is an image and that the length of the title is correct. 
        - If the validation test fails, the user will be alerted with information of what has to be done to create the post. 
        - If the validation test passes, the user will be alerted with a popup asking if they have added all that is needed, or if they want to add more. 
            - If they press done, the post is created, the states are set to initial state, and the user is sent to the "Newsfeed" page. 
            - If they press add more, the user is sent back to the "create post" page. 
    - If the user presses the cancel button, an alert is displayed asking if they really want to leave the page, explaining that what they have done will be lost. 
        - If yes, all fields are set to initial state, and the user is sent to the "Newsfeed" page. 
        - If no, they are sent back to the "create post" page. 
- State handling of images are moved to this component from the child ImagePicker.tsx. 
- Added commented code (which can be uncommented if wanted) that displays the values stored in the post-object. 

Error message if the length of the title is too short: 
<img width="348" alt="Screenshot 2021-01-18 at 17 45 38" src="https://user-images.githubusercontent.com/48119543/104952382-4158e280-59bc-11eb-8dfd-72aa4ca60f46.png">

Cancel button message: 
<img width="349" alt="Screenshot 2021-01-18 at 17 56 05" src="https://user-images.githubusercontent.com/48119543/104952385-428a0f80-59bc-11eb-9b42-94687154628a.png">

Create button message: 
<img width="349" alt="Screenshot 2021-01-18 at 18 04 36" src="https://user-images.githubusercontent.com/48119543/104952388-4322a600-59bc-11eb-8162-f462817169d8.png">

The values of the post object when creating (The commented code): 
<img width="351" alt="Screenshot 2021-01-18 at 17 45 59" src="https://user-images.githubusercontent.com/48119543/104952384-41f17900-59bc-11eb-8291-44ca46d31f31.png">

2021-01-18 19:02 UTC, sp103 submitted a review, later dismissed
Great work, all looks good to me!

2021-01-19 09:25 UTC, calumshep requested changes

2021-01-19 09:25 UTC, calumshep commented on src/Types/types.ts
> +export interface UserObject {
User should have a `name: string;` attribute as well

2021-01-19 09:25 UTC, calumshep commented on src/Components/create-post/CreatePost.tsx
> +            Alert.alert("Sorry, the length of your title must be 5 or more characters.")
Would suggest reducing the minimum title length to 2

2021-01-19 09:25 UTC, calumshep commented on src/Components/Newsfeed.tsx
> +        created_at: "20 minutes ago",
Briefly spoke about this with you - the data stored in the database for `created_at`/`updated_at` looks like: `"2021-01-16T14:27:05.000000Z"` but it's easy in Laravel to convert it into a human-readable time difference such as '20 minutes ago'. Would it be easier if it was returned as a human-readable difference, the original timestamp or both? I'm thinking that you'll need both - the former to actually display but also the latter to work out ordering of posts, etc? But then again the ordering will be chronological in the API response anyway.

I know the migrations file in the api repo has a `timestamps()` entry but it doesn't resolve to a `timestamp` field, it is the method which creates the `created_at`/`updated_at` fields.

2021-01-19 09:31 UTC, wrt95 commented on src/Types/types.ts
> +export interface UserObject {
Fixed

2021-01-19 09:32 UTC, wrt95 commented on src/Components/create-post/CreatePost.tsx
> +            Alert.alert("Sorry, the length of your title must be 5 or more characters.")
Fixed.

2021-01-19 09:37 UTC, wrt95 commented on src/Components/Newsfeed.tsx
> +        created_at: "20 minutes ago",
Yes I know. The reason why it is like this now is because we haven't connected the database to this repo, so I just created some dummy data right now. I assume I will create a function that converts the values from back-end to something readable, which is not hard, but I think we should wait until the connection is made, and until we agree how wee should display the time. 
Agree?

2021-01-19 10:42 UTC, calumshep approved these changes

2021-01-19 10:45 UTC, merged