Adding in login pages and navigation between login and main app navigation
Watt-Dev/SnapThat-PhoneApp pull request #14
Opened 2021-01-22 14:33 UTC by sp103

**Confirmation.tsx**
Page the user sees after registering an account
Navigates to newsfeed
![Confirmation](https://user-images.githubusercontent.com/55585719/105501481-2d62f880-5cbc-11eb-88b3-f960876896d8.PNG)
![ConfirmIOS](https://user-images.githubusercontent.com/55585719/105503598-b24f1180-5cbe-11eb-8d04-51841b9b9404.jpg)

**Login.tsx**
Page the user is first directed to from splashscreen
Navigates to register, passwordreset and newsfeed
![Login](https://user-images.githubusercontent.com/55585719/105501485-2dfb8f00-5cbc-11eb-9d0c-c8032c7eeb7a.PNG)
![LoginIOS](https://user-images.githubusercontent.com/55585719/105503556-a6fbe600-5cbe-11eb-83ac-b2263dc2184a.jpg)

**PasswordReset.tsx**
Page for user to reset password
navigates back to login
![PasswordReset](https://user-images.githubusercontent.com/55585719/105501658-669b6880-5cbc-11eb-8218-79f34811b737.PNG)
![ResetIOS](https://user-images.githubusercontent.com/55585719/105503631-bd09a680-5cbe-11eb-8228-12169daa2981.jpg)

**Register.tsx**
Page for the user to make an account
navigates back to login or to newsfeed
![Register](https://user-images.githubusercontent.com/55585719/105501489-2e942580-5cbc-11eb-84fc-beaee4532a7a.PNG)
![RegisterIOS](https://user-images.githubusercontent.com/55585719/105503643-c09d2d80-5cbe-11eb-8937-1fb331c0176f.jpg)

**SplashScreen.tsx**
Initial screen is shown for 3 seconds
![SplashScreen](https://user-images.githubusercontent.com/55585719/105501490-2e942580-5cbc-11eb-8641-e4eccd9b623f.PNG)
![SplashIOS](https://user-images.githubusercontent.com/55585719/105503651-c3981e00-5cbe-11eb-94c9-98c26dcc6000.jpg)

**AppNavigator.tsx**
displays main app page

**App.tsx**
handles navigation between login pages and main app

2021-01-22 14:43 UTC, wrt95 requested changes
Small stuff to change. 
Mainly, try to have all styling at the same place at the bottom of the files.

2021-01-22 14:43 UTC, wrt95 commented on src/Components/SplashScreen.tsx
> +            />
Can you push style and source one tab in (to the right)?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Confirmation.tsx
> +            />
Can push style and source one tab in (to the right)?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                />
Can you push style and source one tab in (to the right)?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                                <Text onPress={()=> Props.navigation.navigate('PasswordReset')} style={{fontSize:20,color:'#388E3C',textAlign:'left'}}>Forgot?</Text>
Maybe put this <Text> component over several lines for readability?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                <Text style = {styles.subtext}>New To SnapThat?   <Text onPress={()=> Props.navigation.navigate('Register')} style = {styles.link_text}>Sign up</Text></Text>
Maybe put this <Text> component over several lines for readability?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                        <View style={{alignItems:'flex-start'}}><Icon name="caret-left"type="FontAwesome5" onPress={()=> Props.navigation.navigate('Login')} style={{fontSize: 60, color: '#388E3C'}}/>
Maybe put this <View> component over several lines for readability?
Also, create a style element for these components so that its consistent and all styles are at the bottom of the file.

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                        <View style={{width:'100%',alignItems:'center'}}><Text style={styles.main_text}>SNAPTHAT</Text></View>
Maybe put this <View> component over several lines for readability?

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
Can move style down to styles block.

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        <View style={{alignItems:'flex-start'}}><Icon name="caret-left"type="FontAwesome5" onPress={()=> Props.navigation.navigate("Login")} style={{fontSize: 60, color: '#388E3C'}}/>
Maybe put this <View> component over several lines for readability?
And styles down to styles block.

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
styles at bottom

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
styles

2021-01-22 14:43 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
styles

2021-01-22 15:02 UTC, sp103 commented on src/Components/SplashScreen.tsx
> +            />
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Confirmation.tsx
> +            />
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Login.tsx
> +                />
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Login.tsx
> +                                <Text onPress={()=> Props.navigation.navigate('PasswordReset')} style={{fontSize:20,color:'#388E3C',textAlign:'left'}}>Forgot?</Text>
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Login.tsx
> +                <Text style = {styles.subtext}>New To SnapThat?   <Text onPress={()=> Props.navigation.navigate('Register')} style = {styles.link_text}>Sign up</Text></Text>
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/PasswordReset.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Register.tsx
> +                        <View style={{alignItems:'flex-start'}}><Icon name="caret-left"type="FontAwesome5" onPress={()=> Props.navigation.navigate("Login")} style={{fontSize: 60, color: '#388E3C'}}/>
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Register.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
made the changes

2021-01-22 15:02 UTC, sp103 commented on src/Components/login/Register.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
made the changes

2021-01-22 15:17 UTC, wrt95 requested changes
Almost there. Just a few more styles that has to be moved.

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Confirmation.tsx
> +            <View style={{width:'80%'}}><Text style={styles.subtext}>Welcome to the SnapThat family!</Text></View>
Style + put on several lines

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                        style={{borderColor:'#388E3C',borderWidth:4,borderRadius: 15 ,height:60,fontSize:20}}
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                        <View style={{position:'absolute', width:'30%',alignSelf:'flex-end'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Login.tsx
> +                                    style={{fontSize:20,color:'#388E3C',textAlign:'left'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                <View style={{flexDirection:'column',justifyContent:'center'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                    <View style={{flexDirection: 'row', width:'90%'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/PasswordReset.tsx
> +                    <View style={{borderBottomColor: '#388E3C',borderBottomWidth: 3,}}/>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                <View style={{flexDirection:'column',justifyContent:'flex-start'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                    <View style={{flexDirection: 'row', width:'90%'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        <View style={{alignItems:'flex-start'}}>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                        <View style={{width:'100%',alignItems:'center'}}><Text style={styles.main_text}>SNAPTHAT</Text></View>
style

2021-01-22 15:17 UTC, wrt95 commented on src/Components/login/Register.tsx
> +                    <View style={{borderBottomColor: '#388E3C',borderBottomWidth: 3,}}/>
style

2021-01-25 09:54 UTC, wrt95 approved these changes

2021-01-25 09:59 UTC, merged