Button Refactor Base
Watt-Dev/SnapThat-PhoneApp pull request #25
Opened 2021-02-12 15:11 UTC by rb114-hw

### Additions
**ButtonBase.tsx**
- Util file that can be used to create buttons. Currently limited uses but has the ability to expand

### Changes
**DummyPost.tsx**
- Implemented Button Base (with onClickNav function)

**EditProfile.tsx**
- Implemented Button Base

**Profile.tsx**
- Implemented Button Base (with onClickNav function)

**CreatePost.tsx**
- Implemented Button Base

**FAQ.tsx**
- Implemented Button Base (with onClickNav function)

**ManageAccount.tsx**
- Implemented Button Base (with onClickNav function)

**Notifications.tsx**
- Implemented Button Base (with onClickNav function)

**Settings.tsx**
- Implemented Button Base (with onClickNav function)

**ImagePicker.tsx**
- Implemented Button Base
- Left some pre-existing buttons as comments as the current button base is unable to implement the spinner

2021-02-12 15:20 UTC, wrt95 requested changes
@rb114-hw Can you upload photos of how it looks in the different pages?

2021-02-12 15:35 UTC, rb114-hw commented
### Screenshots
**Create Post Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107787478-09d52000-6d47-11eb-918e-0e3e913c0eb8.png)
Selected Image
![image](https://user-images.githubusercontent.com/55586167/107787563-27a28500-6d47-11eb-9faa-26f59b14f1dd.png)

**Profile Page**
Default
![image](https://user-images.githubusercontent.com/55586167/107787710-5f113180-6d47-11eb-8d1a-6d8277d4947f.png)

**Edit Profile Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107787779-751ef200-6d47-11eb-8d6c-75ec2017f758.png)
Image Selected
![image](https://user-images.githubusercontent.com/55586167/107787837-8a941c00-6d47-11eb-999e-32ab1e0927f7.png)

**Post Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107787903-9ed81900-6d47-11eb-87b7-180dca2e6b6b.png)

**Settings Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107787927-aa2b4480-6d47-11eb-8699-c46faff63083.png)

**Manage Acount Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107787961-b7e0ca00-6d47-11eb-8289-9ab66cb0ea7f.png)

**Notifications Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107788004-c7f8a980-6d47-11eb-9412-8aa466d59b13.png)

**FAQ Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107788056-d777f280-6d47-11eb-9c06-57df7c4b8cf1.png)

2021-02-12 16:37 UTC, wrt95 commented
@rb114-hw 
Can we make the cancel changes and cancel post buttons small, but red? 
So for example adding a new property where you specify the colour as a prop for the button? 

Ill comment in the code so you can see.

2021-02-12 17:10 UTC, wrt95 requested changes
This should be it i think! 
Good job, but a little more has to be done

2021-02-12 17:10 UTC, wrt95 commented on src/Components/Profile/Logged-in-user/Profile.tsx
> +                    <ButtonBase buttonText="Edit Profile" icon="edit" onClick={onClickNavigate} buttonType="small" />
<ButtonBase buttonText="Edit Profile" icon="edit" onClick={onClickNavigate} buttonType="small" colour="green" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/create-post/CreatePost.tsx
> +                    <ButtonBase buttonText="Create" icon="save" onClick={checkValidPost} buttonType="small" />
<ButtonBase buttonText="Create" icon="save" onClick={checkValidPost} buttonType="small" colour="green" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/create-post/CreatePost.tsx
> +                    <ButtonBase buttonText="Cancel Post" onClick={doCancel} buttonType="cancel" />
<ButtonBase buttonText="Cancel Post" onClick={doCancel} buttonType="small" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/settings/FAQ/FAQ.tsx
> +                <ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="cancel" />
<ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="large" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/settings/ManageAccount.tsx
> +                <ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="cancel" />
<ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="large" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/settings/Notifications/Notifications.tsx
> +                <ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="cancel" />
<ButtonBase buttonText="Return to Settings" onClick={onClickReturn} buttonType="large" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/settings/Settings.tsx
> +            <ButtonBase buttonText="Log Out" onClick={onClickReturn} buttonType="cancel" />
<ButtonBase buttonText="Log Out" onClick={onClickReturn} buttonType="large" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +    buttonType: "small" | "cancel" | "regular";
change to: 
buttonType: "small" | "large";

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +    const iconPicker = () => {
Can simplify this function to: 

```
    const iconPicker = () => {
        return props.icon ?
            <Icon
                name={props.icon}
                type="FontAwesome5"
                style={styles.button_icon}
        /> : <></>
```

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +                        style={styles.small_button}
style={props.colour === "green" ? styles.small_button_green : styles.small_button_red}

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +            case "cancel":
case "large":

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +                        style={styles.cancel_button}
style={props.colour === "green" ? styles.large_button_green : styles.large_button_red}

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +            case "regular":
delete

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +    small_button: {
small_button_red: {}
small_button_green: {}

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +    cancel_button: {
large_button_red: {}
large_button_green: {}

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ImagePicker.tsx
> +                    <ButtonBase buttonText="Remove Image" icon="times" onClick={removeImage} buttonType="cancel" />
<ButtonBase buttonText="Remove Image" icon="times" onClick={removeImage} buttonType="large" colour="red" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ImagePicker.tsx
> +                    <ButtonBase buttonText="Take Photo" icon="camera" onClick={launchCameraOnPhone} buttonType="regular" />
<ButtonBase buttonText="Take Photo" icon="camera" onClick={launchCameraOnPhone} buttonType="large" colour="green" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ImagePicker.tsx
> +                    <ButtonBase buttonText="Choose from Library" icon="images" onClick={launchLibraryFromPhone} buttonType="regular" />
<ButtonBase buttonText="Choose from Library" icon="images" onClick={launchLibraryFromPhone} buttonType="large" colour="green" />

2021-02-12 17:10 UTC, wrt95 commented on src/Components/util/ButtonBase.tsx
> +        width: 320,
width: 300

2021-02-12 17:49 UTC, rb114-hw commented
Suggestions Implemented! I'll need to sort out the css elements of the large/small buttons. Then everything should fall into place

2021-02-12 19:02 UTC, rb114-hw commented
### Updated Screenshots
**Create Post Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107809613-49aa0080-6d63-11eb-9cf7-6a6413bf3830.png)
Image selected
![image](https://user-images.githubusercontent.com/55586167/107809728-74945480-6d63-11eb-9a91-880e2cfbc298.png)

**Profile Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107809769-88d85180-6d63-11eb-9cfe-9deb86e98602.png)

**Post Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107809810-9b528b00-6d63-11eb-9923-9260a7f0e2a0.png)

**Edit Profile Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107809873-b1604b80-6d63-11eb-9319-e713b4721968.png)
Image Selected
![image](https://user-images.githubusercontent.com/55586167/107809912-c1782b00-6d63-11eb-92bf-47cd653e913b.png)

**Settings Page**
Defualt
![image](https://user-images.githubusercontent.com/55586167/107810399-80344b00-6d64-11eb-94b2-fa9fdc2eec65.png)

2021-02-13 12:19 UTC, calumshep requested changes
Not sure how up-to-date the photos in the most recent comment on this PR are, but I have a couple of suggestions:

- Make the buttons all the same width (so Save and Cancel buttons on create post page are the same width as the choose photo images for example)
- Reduce the font size within buttons to increase spacing around the text

2021-02-13 14:22 UTC, wrt95 commented
@calumshep 
Photos are not up to date. All sizes are fixed, and we have 3 types of buttons (small, large and small-rounded). It all looks very good. Save and Cancel are now the same size (see comments on Teams). 
Font size is also reduced.

2021-02-13 14:27 UTC, wrt95 commented
@calumshep 
Looks like this now, which I think is how we want it to be for now. 
<img width="357" alt="Screenshot 2021-02-13 at 14 26 19" src="https://user-images.githubusercontent.com/48119543/107852231-892a2880-6e07-11eb-8116-b83b0cc374a6.png">
<img width="346" alt="Screenshot 2021-02-13 at 14 26 14" src="https://user-images.githubusercontent.com/48119543/107852233-8b8c8280-6e07-11eb-8c4b-07c1c6b42e12.png">
<img width="365" alt="Screenshot 2021-02-13 at 14 26 10" src="https://user-images.githubusercontent.com/48119543/107852234-8cbdaf80-6e07-11eb-8e31-47145ff03275.png">
<img width="366" alt="Screenshot 2021-02-13 at 14 26 06" src="https://user-images.githubusercontent.com/48119543/107852235-8cbdaf80-6e07-11eb-9757-43ada9942e92.png">
<img width="360" alt="Screenshot 2021-02-13 at 14 26 01" src="https://user-images.githubusercontent.com/48119543/107852236-8d564600-6e07-11eb-8c27-81aae374d14d.png">
<img width="363" alt="Screenshot 2021-02-13 at 14 25 54" src="https://user-images.githubusercontent.com/48119543/107852237-8deedc80-6e07-11eb-8fd0-22323fd19df2.png">
<img width="355" alt="Screenshot 2021-02-13 at 14 25 50" src="https://user-images.githubusercontent.com/48119543/107852239-8e877300-6e07-11eb-9256-295ace84f7ea.png">
<img width="368" alt="Screenshot 2021-02-13 at 14 25 42" src="https://user-images.githubusercontent.com/48119543/107852241-8f200980-6e07-11eb-988e-241fe5ac3d88.png">
<img width="364" alt="Screenshot 2021-02-13 at 14 25 32" src="https://user-images.githubusercontent.com/48119543/107852244-8fb8a000-6e07-11eb-9ef8-df75cccab28b.png">

2021-02-14 09:40 UTC, calumshep commented
Yep, mostly looks good now with the three consistent button types. Just one small thing - the text and icon inside the Create/Save/Edit Profile buttons is off-centre and I suspect it may be because the font-awesome icon has too much right-padding? Is this something you can fix?

2021-02-14 14:21 UTC, sp103 submitted a review, later dismissed
all looks good to me

2021-02-14 14:26 UTC, wrt95 commented
@calumshep 

Good spotted! 
Actually, no paddingRight was involved. The reason of the not centring with icons was that the Icon didnt have a <Text> block around it. 

This code solved the issue: 
```<Text style={styles.icon_container}>{iconPicker()}</Text>```

Photos: 
<img width="341" alt="Screenshot 2021-02-14 at 14 23 41" src="https://user-images.githubusercontent.com/48119543/107879416-87786780-6ed0-11eb-9311-400d8cc81bbf.png">
<img width="353" alt="Screenshot 2021-02-14 at 14 23 20" src="https://user-images.githubusercontent.com/48119543/107879419-8b0bee80-6ed0-11eb-921c-277b47bef964.png">

2021-02-14 19:38 UTC, calumshep approved these changes

2021-02-14 21:06 UTC, wrt95 approved these changes

2021-02-14 21:07 UTC, merged